CREATE TABLE ACCOUNT
(
    ID INTEGER NOT NULL,
    ACCOUNT_NUMBER VARCHAR(20) NOT NULL,
    BALANCE INTEGER NOT NULL
);
CREATE TABLE ADMIN
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    LOGIN VARCHAR(32) NOT NULL,
    PASSWORD VARCHAR(32) NOT NULL,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL
);
CREATE TABLE ANNOUNCEMENT
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    BODY_EN VARCHAR(15000),
    TITLE_EN VARCHAR(1000),
    POST_DATE TIMESTAMP DEFAULT NOW(),
    BODY_RU VARCHAR(15000),
    TITLE_RU VARCHAR(1000)
);
CREATE TABLE CLIENT
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    LOGIN VARCHAR(32) NOT NULL,
    PASSWORD VARCHAR(32) NOT NULL,
    BONUS DECIMAL(65535,32767) DEFAULT 0 NOT NULL
);
CREATE TABLE COMMENT
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    CLIENT_ID BIGINT,
    COMMENT_BODY VARCHAR(1000),
    LEAVE_DATE TIMESTAMP DEFAULT NOW()
);
CREATE TABLE DISPATCHER
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    LOGIN VARCHAR(32) NOT NULL,
    PASSWORD VARCHAR(32) NOT NULL,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    NATIONAL_ID VARCHAR(13) NOT NULL,
    PHONE VARCHAR(20) NOT NULL
);
CREATE TABLE DRIVER
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    LOGIN VARCHAR(32) NOT NULL,
    PASSWORD VARCHAR(32) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    FIRST_NAME VARCHAR(50) NOT NULL,
    NATIONAL_ID VARCHAR(13) NOT NULL,
    PHONE VARCHAR(32) NOT NULL,
    AVAILABLE BOOLEAN DEFAULT TRUE NOT NULL,
    CURRENT_LOCATION VARCHAR(100) DEFAULT 'NULL',
    GOV_NUMBER VARCHAR(15),
    CAR_MODEL VARCHAR(100),
    CAR_CLASS VARCHAR(32)
);
CREATE TABLE ORDERS
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    CLIENT_ID BIGINT NOT NULL,
    CAR_CLASS VARCHAR(50),
    PICKUP_LOCATION VARCHAR(100),
    DROP_OFF_LOCATION VARCHAR(100),
    RECEIVED_TIME TIMESTAMP DEFAULT NOW() NOT NULL,
    DRIVER_ID BIGINT,
    COST DECIMAL(65535,32767),
    STATUS_ID INTEGER DEFAULT 1,
    DISPATCHER_ID BIGINT
);
CREATE TABLE STATUS
(
    ID INTEGER PRIMARY KEY NOT NULL,
    VALUE VARCHAR(32) NOT NULL
);
CREATE TABLE USER
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    LOGIN VARCHAR(2147483647) NOT NULL
);
ALTER TABLE COMMENT ADD FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (ID);
CREATE INDEX CONSTRAINT_63_INDEX_D ON COMMENT (CLIENT_ID);
CREATE UNIQUE INDEX CONSTRAINT_8B72_INDEX_7 ON DISPATCHER (ID);
CREATE UNIQUE INDEX UNIQUE_LOGIN_INDEX_7 ON DISPATCHER (LOGIN);
CREATE UNIQUE INDEX UNIQUE_NATIONAL_ID_INDEX_7 ON DISPATCHER (NATIONAL_ID);
CREATE UNIQUE INDEX "unique_NATIONAL_ID_INDEX_4" ON DRIVER (NATIONAL_ID);
CREATE INDEX "CURRENT_LOCATION_index" ON DRIVER (CURRENT_LOCATION);
ALTER TABLE ORDERS ADD FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (ID);
ALTER TABLE ORDERS ADD FOREIGN KEY (DISPATCHER_ID) REFERENCES DISPATCHER (ID);
ALTER TABLE ORDERS ADD FOREIGN KEY (DRIVER_ID) REFERENCES DRIVER (ID);
ALTER TABLE ORDERS ADD FOREIGN KEY (STATUS_ID) REFERENCES STATUS (ID);
CREATE INDEX CONSTRAINT_8B7_INDEX_1 ON ORDERS (DRIVER_ID);
CREATE INDEX CONSTRAINT_8B_INDEX_1 ON ORDERS (STATUS_ID);
CREATE INDEX CONSTRAINT_8_INDEX_1 ON ORDERS (CLIENT_ID);
